language: python
sudo: false

python:
  - "3.2"
  - "3.3"
  - "3.4"

install: "pip install docutils coveralls"

script: 
    - "coverage run do_test.py"
    - "coverage run setup.py check --strict --metadata"

after-success:
    - "coveralls"

