language: python
sudo: false
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

script: "python test.py"

after_success:
  - "python verchg.py"
  - "python setup.py register"
  - "python setup.py sdist upload"