language: python
sudo: false

python:
  - "3.3"
  - "3.4"

install: "pip install docutils coveralls setuptools"

script: 
    - "python setup.py check --strict --metadata"
    - "coverage run setup.py test"

after_success:
    - "coveralls"

