language: python
sudo: false

python:
  - "3.3"
  - "3.4"

install: "pip install docutils coveralls"

script: 
    - "coverage run --source=NumRep do_test.py"
    - "coverage run --source=NumRep setup.py check --strict --metadata"

after_success:
    - "coveralls"

