language: python
sudo: false

python:
  - "3.3"
  - "3.4"

install: "pip install docutils coveralls"

script: 
    - "python setup.py check --strict --metadata"
    - "coverage run do_test.py"

after_success:
    - "coveralls"

